version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_MESSAGE_MAXSIZE=256  # Increase the max message size to 256 MB
      - SPARK_CONF_DIR=/opt/bitnami/spark/conf  # Set Spark conf directory
    ports:
      - "8080:8080"  # Spark UI
      - "7077:7077"  # Spark master port
    volumes:
      - ./workspace:/workspace  # Mount the current directory into the container
      - ./conf:/opt/bitnami/spark/conf  # Mount custom config directory
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_RPC_MESSAGE_MAXSIZE=256  # Increase the max message size to 256 MB
      - SPARK_CONF_DIR=/opt/bitnami/spark/conf  # Set Spark conf directory
    depends_on:
      - spark-master
    volumes:
      - ./conf:/opt/bitnami/spark/conf  # Mount custom config directory
    networks:
      - spark-network

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=SparkCassandraCluster
      - CASSANDRA_LISTEN_ADDRESS=cassandra
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra
    ports:
      - "9042:9042"  # Cassandra port
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./scripts/init.cql:/docker-entrypoint-initdb.d/init.cql
    networks:
      - spark-network

volumes:
  cassandra-data:

networks:
  spark-network:
    driver: bridge
