version: '3.8'

services:
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - ./spark-cassandra-test/spark-cassandra-connector_2.12-3.3.0.jar:/opt/bitnami/spark/jars/spark-cassandra-connector_2.12-3.3.0.jar
    ports:
      - 8080:8080
    networks:
      - spark-network
  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
