version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_KEYSPACE=test_keyspace
    ports:
      - "9042:9042"
    networks:
      - spark-cassandra-net

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - ./spark-cassandra-test/spark-cassandra-connector_2.12-3.3.0.jar:/opt/bitnami/spark/jars/spark-cassandra-connector_2.12-3.3.0.jar
    ports:
      - 8080:8080
    networks:
      - spark-cassandra-net  # Correction ici pour utiliser le même réseau

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    networks:
      - spark-cassandra-net  # Correction ici aussi pour utiliser le même réseau

networks:
  spark-cassandra-net:  # Réseau défini ici
    driver: bridge
